create database basededatos1;
use basededatos1;
CREATE USER 'agustin' IDENTIFIED BY '123456';
grant all privileges on basededatos1.* to 'agustin'@'%';

CREATE TABLE CLIENTES (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(128) NOT NULL,
    COMENTARIOS VARCHAR (350) NOT NULL);

CREATE TABLE TIPOS_CONTACTO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(128) NOT NULL);

 CREATE TABLE CONTACTOS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CONTACTO VARCHAR(1024) NOT NULL,
    TIPO_CONTACTO_ID INT NOT NULL,
    CLIENTE_ID INT NOT NULL,
    FOREIGN KEY (TIPO_CONTACTO_ID) REFERENCES TIPOS_CONTACTO(ID),
    FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES(ID));
	
CREATE TABLE FACTURAS (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	LETRA VARCHAR (10) NOT NULL,
	SUCURSAL VARCHAR (100) NOT NULL,
	NUMERO INT,
	CLIENTE_ID INT NOT NULL,
	FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES(ID));
	
CREATE TABLE DETALLE_FACTURA (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	CANTIDAD INT NOT NULL,
	PRECIO DOUBLE NOT NULL,
	SUB_TOTAL DOUBLE NOT NULL,
	FACTURA_ID INT NOT NULL,
	PRODUCTO_ID INT NOT NULL,
	FOREIGN KEY (FACTURA_ID) REFERENCES FACTURAS(ID),
	FOREIGN KEY (PRODUCTO_ID) REFERENCES PRODUCTOS(ID));
	
CREATE TABLE PRODUCTOS (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	NOMBRE VARCHAR(1024));
